#!/usr/bin/env bash
# install.sh — environment setup script for the lunel image
#
# Provides:
#   1) setup-shell-source  run once at build time: source env.sh on shell start
#   2) install coding environments (go/rust/node-tools) and Agent CLI packages
#      (opencode/codex/pi/lunel-cli) on demand at runtime.
set -euo pipefail

CACHE="${LUNEL_CACHE:-/home/lunel/cache}"

log() { echo "[install] $*"; }

# ---- Build-time function: shell source ----
setup_shell_source() {
  local snippet='for __f in /home/lunel/cache/*/env.sh; do [ -r "$__f" ] && . "$__f"; done'
  local rc="$HOME/.profile"
  touch "$rc" 2>/dev/null || return 0
  grep -q 'cache/\*/env.sh' "$rc" 2>/dev/null && return 0
  printf '\n# lunel coding tool environment variables\n%s\n' "$snippet" >> "$rc"
  log "shell source hook written to $rc"
}

# ---- Runtime function: install tools ----
FORCE=0
for a in "$@"; do
  case "$a" in
    --update|-u) FORCE=1 ;;
  esac
done

ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)  GO_ARCH=amd64 ;;
  aarch64|arm64) GO_ARCH=arm64 ;;
  *) echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac

write_tool_env() {
  local dir="$1"; shift
  mkdir -p "$dir"
  local f="$dir/env.sh"
  {
    echo "# Coding tool environment variables (generated by install.sh, at $dir/env.sh)"
    for line in "$@"; do
      echo "export $line"
    done
  } > "$f"
}

# ---- Go ----
install_go() {
  local dir="$CACHE/go"
  if [ "$FORCE" -eq 0 ] && [ -x "$dir/bin/go" ]; then
    log "Go already installed (skip download)"
  else
    [ "$FORCE" -eq 1 ] && rm -rf "$dir"
    mkdir -p "$dir"
    log "Downloading and installing Go (extract to $dir)..."
    curl -fsSL https://go.dev/dl/?mode=json -o /tmp/golang-dl.json
    GO_VER="$(awk -F'"' '/"version":/{gsub(/^go/,"",$4); print $4; exit}' /tmp/golang-dl.json)"
    TMP="/tmp/go-${GO_VER}.linux-${GO_ARCH}.tar.gz"
    curl -fsSL "https://go.dev/dl/go${GO_VER}.linux-${GO_ARCH}.tar.gz" -o "$TMP"
    tar -C "$dir" -xzf "$TMP" --strip-components=1
    rm -f "$TMP" /tmp/golang-dl.json
    log "Go $GO_VER installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "GOROOT=$dir" \
    "GOPATH=$CACHE/go-pkg" \
    "GOCACHE=$CACHE/go-build" \
    "GOFLAGS=-mod=mod" \
    "PATH=$dir/bin:$CACHE/go-pkg/bin:\$PATH"
}

# ---- Rust ----
install_rust() {
  local rustup_home="$CACHE/rustup"
  local cargo_home="$CACHE/cargo"
  if [ "$FORCE" -eq 0 ] && [ -x "$cargo_home/bin/cargo" ]; then
    log "Rust already installed (skip download)"
  elif [ "$FORCE" -eq 1 ] && [ -x "$cargo_home/bin/rustup" ]; then
    log "Updating Rust ..."
    RUSTUP_HOME="$rustup_home" CARGO_HOME="$cargo_home" "$cargo_home/bin/rustup" update stable >/dev/null 2>&1 || true
    log "Rust updated"
  else
    mkdir -p "$rustup_home" "$cargo_home"
    log "Downloading and installing Rust (directly into $rustup_home / $cargo_home)..."
    export RUSTUP_HOME="$rustup_home"
    export CARGO_HOME="$cargo_home"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o /tmp/rustup-init.sh
    RUSTUP_HOME="$rustup_home" CARGO_HOME="$cargo_home" \
      sh /tmp/rustup-init.sh -y --default-toolchain stable --profile minimal --no-modify-path
    rm -f /tmp/rustup-init.sh
    log "Rust installed"
  fi
  write_tool_env "$cargo_home" \
    "RUSTUP_HOME=$rustup_home" \
    "CARGO_HOME=$cargo_home" \
    "PATH=$cargo_home/bin:$rustup_home/bin:\$PATH"
}

# ---- Node global tools ----
install_node_tools() {
  local dir="$CACHE/npm-global"
  if [ "$FORCE" -eq 0 ] && [ -x "$dir/bin/tsc" ]; then
    log "TypeScript already installed (skip download)"
  else
    mkdir -p "$dir"
    log "Installing TypeScript (npm --prefix $dir)..."
    if [ "$FORCE" -eq 1 ]; then npm i -g --prefix "$dir" typescript@latest; else npm i -g --prefix "$dir" typescript; fi
    log "TypeScript installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "npm_config_cache=$CACHE/npm" \
    "npm_config_prefix=$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Agent CLI: Lunel CLI ----
install_lunel_cli() {
  local dir="$CACHE/lunel-cli"
  local bin="$dir/bin/lunel-cli"
  if [ "$FORCE" -eq 0 ] && [ -x "$bin" ]; then
    log "Lunel CLI already installed (skip)"
  else
    log "Installing Lunel CLI (npm --prefix $dir)..."
    mkdir -p "$dir"
    npm install --prefix "$dir" "lunel-cli${FORCE:+@latest}"
    link_npm_bins "$dir"
    log "Lunel CLI installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "npm_config_cache=$CACHE/npm" \
    "npm_config_prefix=$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Agent CLI: OpenCode ----
install_opencode() {
  local dir="$CACHE/opencode"
  local bin="$dir/bin/opencode"
  if [ "$FORCE" -eq 0 ] && [ -x "$bin" ]; then
    log "OpenCode already installed (skip)"
  else
    log "Installing OpenCode (npm --prefix $dir)..."
    mkdir -p "$dir"
    npm install --prefix "$dir" "opencode-ai${FORCE:+@latest}"
    link_npm_bins "$dir"
    log "OpenCode installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "npm_config_cache=$CACHE/npm" \
    "npm_config_prefix=$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Agent CLI: OpenAI Codex ----
install_codex() {
  local dir="$CACHE/codex"
  local bin="$dir/bin/codex"
  if [ "$FORCE" -eq 0 ] && [ -x "$bin" ]; then
    log "Codex already installed (skip)"
  else
    log "Installing Codex (npm --prefix $dir)..."
    mkdir -p "$dir"
    npm install --prefix "$dir" "@openai/codex${FORCE:+@latest}"
    link_npm_bins "$dir"
    log "Codex installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "npm_config_cache=$CACHE/npm" \
    "npm_config_prefix=$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Agent CLI: Pi ----
install_pi() {
  local dir="$CACHE/pi"
  local bin="$dir/bin/pi"
  if [ "$FORCE" -eq 0 ] && [ -x "$bin" ]; then
    log "Pi already installed (skip)"
  else
    log "Installing Pi (npm --prefix $dir)..."
    mkdir -p "$dir"
    npm install --prefix "$dir" "@earendil-works/pi-coding-agent${FORCE:+@latest}"
    link_npm_bins "$dir"
    log "Pi installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "npm_config_cache=$CACHE/npm" \
    "npm_config_prefix=$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Helper: link npm bin entries after --prefix install ----
link_npm_bins() {
  local dir="$1"
  mkdir -p "$dir/bin"
  for pkg_json in "$dir/node_modules/"*/package.json "$dir/node_modules/"@*/*/package.json; do
    [ -f "$pkg_json" ] || continue
    local pkg_dir
    pkg_dir="$(dirname "$pkg_json")"
    local bins
    bins=$(node -e "
      const p = require('$pkg_json');
      const b = p.bin;
      if (!b) process.exit(0);
      if (typeof b === 'string') console.log(Object.keys(p.bin || {'dummy':1})[0] + '|' + b);
      else Object.entries(b).forEach(([k,v]) => console.log(k + '|' + v));
    " 2>/dev/null) || continue
    echo "$bins" | while IFS='|' read -r name relpath; do
      [ -z "$name" ] && continue
      local src="$pkg_dir/$relpath"
      if [ -f "$src" ]; then
        ln -sf "$src" "$dir/bin/$name"
        chmod +x "$dir/bin/$name"
      fi
    done
  done
}

usage() {
  cat <<'USAGE'
Usage: install.sh <subcommand> [options]

  Run once at build time:
    setup-shell-source   write env.sh sourcing hook into ~/.profile

  Install coding environments on demand at runtime:
     go            Go toolchain
     rust          Rust toolchain
     node-tools    TypeScript etc. npm global packages

  Install Agent CLI packages on demand at runtime:
     lunel-cli     Lunel CLI
     opencode      OpenCode AI
     codex         OpenAI Codex
     pi            Pi AI

  Options:
     --update, -u   force reinstall / update to the latest

  Examples:
   install.sh setup-shell-source         # only used at image build time
   install.sh go rust                     # install Go + Rust
   install.sh lunel-cli opencode          # install Lunel CLI + OpenCode
   install.sh opencode codex pi --update          # upgrade all three agents
USAGE
}

# Subcommand dispatch
case "${1:-}" in
  setup-shell-source)
    setup_shell_source
    exit 0
    ;;
  -h|--help|help|"")
    usage
    exit 0
    ;;
esac

# Runtime install logic
TARGETS=()
for a in "$@"; do
  case "$a" in
    --update|-u) ;;
    -h|--help|help) usage; exit 0 ;;
    *) TARGETS+=("$a") ;;
  esac
done

if [ "${#TARGETS[@]}" -eq 0 ]; then
  usage
  exit 0
fi

for t in "${TARGETS[@]}"; do
  case "$t" in
     go)            install_go ;;
     rust)          install_rust ;;
     node-tools|ts) install_node_tools ;;
     lunel-cli)     install_lunel_cli ;;
     opencode)      install_opencode ;;
     codex)         install_codex ;;
     pi)            install_pi ;;
      *) echo "Unknown target: $t" >&2; usage; exit 1 ;;
  esac
done

setup_shell_source

log "Done. Each tool's environment variables were written to its install dir's env.sh,"
log "and the import statement was written to ~/.profile."
