# 完整版（:full）：在 Dockerfile 基础上追加可选插件
ARG CADDY_VERSION=2.11.4
FROM caddy:builder AS builder
RUN xcaddy build \
  --with github.com/caddy-dns/cloudflare \
  --with github.com/caddy-dns/alidns \
  --with github.com/mholt/caddy-l4 \
  --with github.com/mholt/caddy-dynamicdns \
  --with github.com/mholt/caddy-webdav \
  --with github.com/abiosoft/caddy-exec \
  --with github.com/WingLim/caddy-webhook

FROM caddy:${CADDY_VERSION}
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
