#!/usr/bin/env bash
# =============================================================================
# install.sh — dispatcher for the pi development image setup scripts
#
# This is a thin loader. The actual installers live in install.d/ (in the s6
# overlay tree, /etc/s6-overlay/scripts/install.d/): one file per language
# toolchain / task. Adding a new install = drop one new script in that directory
# (defining install_<name>()), no changes to this file.
#
# Two kinds of functionality in the image:
#   1) language toolchains  install.sh <go|rust|java|...>          (on-demand download)
#   2) pi plugins           install.sh plugins [all|--core|...]    (batch npm install)
#
# Install locations (both persist across container recreation):
#   language toolchains -> $PI_CACHE (default /home/pi/cache, the data/cache volume)
#   pi plugins           -> ~/.pi/agent (the data/pi volume); build-time "plugins all" is
#                           used by the Dockerfile to bake the curated set into the image
#                           at /home/pi/.pi-plugins (outside the volume)
#
# Usage (in the container, or from the host via `docker compose exec pi install.sh ...`):
#   install.sh setup-bash-env            build-time only (run as root, see setup_bash_env)
#   install.sh go rust node-tools        install language toolchains on demand (independent)
#   install.sh go --update               force reinstall/update to latest
#   install.sh plugins --core            install only the core plugin group
#   install.sh plugins all               install all plugin groups
#   install.sh --help                    show full usage
#
# Notes:
#   - Safe to re-run: already-installed toolchains/plugins are skipped; --update forces reinstall.
#   - `pi install` accepts one source at a time, so plugins are installed one-by-one; a single
#     failure does not abort the rest.
#   - Plugins are installed per group, one plugin per category, to avoid tool-name collisions.
#   - IM channels (Telegram/Feishu/WeChat) still need their own bot tokens after install, see README.
# =============================================================================
set -euo pipefail

CACHE="${PI_CACHE:-/home/pi/cache}"
INSTALL_D="${PI_INSTALL_D:-/etc/s6-overlay/scripts/install.d}"

log() { echo "[install] $*"; }

# =============================================================================
# 1. Args and architecture detection
# =============================================================================

# ---- Architecture (amd64 / arm64) for picking the right download packages ----
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)        GO_ARCH=amd64 ;;
  aarch64|arm64) GO_ARCH=arm64 ;;
  *) echo "[install] unsupported architecture: $ARCH" >&2; exit 1 ;;
esac

# ---- Build the tool list from install.d/ (no hardcoded registry here) ----
list_tools() {
  local f t desc
  for f in "$INSTALL_D"/*.sh; do
    [ -f "$f" ] || continue
    t="$(basename "$f" .sh)"
    case "$t" in setup-bash-env|plugins) continue ;; esac
    desc="$(sed -n 's/^# *desc: //p' "$f" | head -1)"
    printf '    %-18s %s\n' "$t" "$desc"
  done
}

usage() {
  cat <<'USAGE'
Usage: install.sh <subcommand|tool> [options]

  [build-time only, needs root]
    setup-bash-env   write /etc/pi-env.sh that sources each tool's env.sh (see BASH_ENV note)

  [language toolchains, multiple allowed, independent]

USAGE
  list_tools | sort
  cat <<'USAGE'

  [options]
    --update, -u   force reinstall/update language toolchains to latest (default skips if installed)
    --help, -h     show this help

  [examples]
    install.sh go rust node-tools        # install Go + Rust + TypeScript
    install.sh java kotlin               # install Java + Kotlin (Kotlin auto-installs JDK first)
    install.sh plugins --core            # install only the core plugin group
    install.sh plugins all               # install all plugin groups
USAGE
}

# =============================================================================
# 2. Shared helpers (sourced install.d scripts use these)
# =============================================================================

# Writes a tool's env.sh (overwrite, idempotent), persisted together with the tool in cache.
# After container recreation and re-mounting the cache, re-running install reuses them.
# Usage: write_tool_env <tool dir> <"VAR=value" ...>
write_tool_env() {
  local dir="$1"; shift
  mkdir -p "$dir"
  local f="$dir/env.sh"
  {
    echo "# Coding tool environment variables (generated by install.sh, at $dir/env.sh)"
    for line in "$@"; do
      echo "export $line"
    done
  } > "$f"
}

# Writes the `source` snippet importing each tool's env.sh into both ~/.profile (login shells)
# and ~/.bashrc (interactive non-login shells, e.g. `docker compose exec -it pi bash`), so the
# installed toolchain environment is available in interactive shells too. Skips if already present.
# pi loads the env via BASH_ENV in non-interactive shells (see setup_bash_env / Dockerfile).
setup_shell_source() {
  local snippet='for __f in /home/pi/cache/*/env.sh; do [ -r "$__f" ] && . "$__f"; done'
  local rc
  for rc in "$HOME/.profile" "$HOME/.bashrc"; do
    touch "$rc" 2>/dev/null || continue
    grep -q 'cache/\*/env.sh' "$rc" 2>/dev/null && continue
    printf '\n# pi coding tool environment variables (source each tool dir'"'"'s env.sh)\n%s\n' "$snippet" >> "$rc"
  done
}

# =============================================================================
# 3. Dispatch
# =============================================================================

# Source every install.d script once so install_*() functions (and cross-tool
# deps like scala/kotlin -> install_java) are all defined in this shell.
load_all() {
  local f
  for f in "$INSTALL_D"/*.sh; do
    [ -f "$f" ] && . "$f"
  done
}

install_tools() {
  local a t
  FORCE=0
  TARGETS=()
  for a in "$@"; do
    case "$a" in
      --update|-u) FORCE=1 ;;
      -h|--help|help) usage; exit 0 ;;
      *) TARGETS+=("$a") ;;
    esac
  done

  # " (updated)" suffix shown in install logs only on a real --update reinstall.
  # FORCE is an integer (0/1): the old ${FORCE:+(updated)} form wrongly showed the
  # suffix whenever FORCE was set to 0, because "0" is a non-empty string.
  UPDATED_TAG=""
  [ "$FORCE" -eq 1 ] && UPDATED_TAG=" (updated)"

  if [ "${#TARGETS[@]}" -eq 0 ]; then
    usage
    exit 0
  fi

  load_all

  for t in "${TARGETS[@]}"; do
    case "$t" in
      ts) t=node-tools ;;
      node-tools) t=node_tools ;;  # hyphen -> underscore: bash fn names can't contain '-'
    esac
    if declare -F "install_${t}" >/dev/null 2>&1; then
      "install_${t}"
    else
      echo "unknown tool: $t" >&2
      usage
      exit 1
    fi
  done

  setup_shell_source
  log "Language toolchains installed. Each tool's environment was written to its dir's env.sh (e.g. cache/go/env.sh),"
  log "and the import statement was written to ~/.profile and ~/.bashrc. Effective immediately in the pi process (via BASH_ENV);"
  log "the interactive shell picks it up on reopen."
}

# =============================================================================
# install_gc — clean on-demand toolchains from the cache to reclaim disk.
#
# Usage:
#   install.sh gc              list every cached tool with its size
#   install.sh gc go rust ...  remove only the named tools
#   install.sh gc --all        remove every cached toolchain
#
# Tool dirs live under $CACHE (data/cache volume), each holding its env.sh, and
# are named after the tool. Removing a dir also drops its env.sh so the tool no
# longer loads on next shell/pi session. Skips anything not in the cache.
# =============================================================================
install_gc() {
  local action="${1:-}"
  [ -d "$CACHE" ] || { log "gc: no cache at $CACHE"; return 0; }

  if [ "$action" = "--all" ] || [ "$action" = "-a" ]; then
    echo "[install] gc: removing ALL cached toolchains in $CACHE"
    for d in "$CACHE"/*/; do
      [ -d "$d" ] || continue
      rm -rf "$d"
      echo "  removed $(basename "$d")"
    done
    echo "[install] gc: cache cleared"
    return 0
  fi

  if [ -z "$action" ] || [ "$action" = "--list" ] || [ "$action" = "-l" ]; then
    echo "[install] gc: cached toolchains in $CACHE:"
    local any=0
    for d in "$CACHE"/*/; do
      [ -d "$d" ] || continue
      any=1
      printf '  %-14s %s\n' "$(basename "$d")" "$(du -sh "$d" 2>/dev/null | awk '{print $1}')"
    done
    [ "$any" -eq 1 ] || echo "  (none)"
    echo
    echo "  Remove specific tools: install.sh gc <go> <rust> ...   or all: install.sh gc --all"
    return 0
  fi

  # explicit tool names
  for t in "$@"; do
    local dir="$CACHE/$t"
    if [ -d "$dir" ]; then
      local size
      size="$(du -sh "$dir" 2>/dev/null | awk '{print $1}')"
      rm -rf "$dir"
      log "gc: removed $t ($size)"
    else
      log "gc: no cached tool named '$t' (nothing removed)"
    fi
  done
}

# =============================================================================
# 4. Top-level dispatch
# =============================================================================
case "${1:-}" in
  setup-bash-env)
    load_all
    install_setup_bash_env
    ;;
  plugins)
    shift
    load_all
    install_plugins "${1:-all}"
    ;;
  -h|--help|help|"")
    usage
    ;;
  gc|clean)
    shift
    install_gc "$@"
    ;;
  *)
    install_tools "$@"
    ;;
esac