#!/usr/bin/env bash
# install.sh — environment setup script for the paseo image (shared at build time and runtime)
#
# Two main functions:
#   1) setup-bash-wrap  run once at build time (as root): rename the real bash to bash.real,
#      and wrap /usr/bin/bash so it sources each tool's env.sh on startup.
#   2) install coding environments (go/rust/python/node-tools) and Agent CLI packages
#      (claude-code/codex/opencode-ai) on demand at runtime.
set -euo pipefail

CACHE="${PASEO_CACHE:-/home/paseo/cache}"

log() { echo "[install] $*"; }

# ---- Build-time function: bash wrapper ----
setup_bash_wrap() {
  cp /usr/bin/bash /usr/bin/bash.real
  rm -f /usr/bin/bash
  cat > /usr/bin/bash <<EOF
#!/usr/bin/bash.real
for __f in ${CACHE}/*/env.sh; do [ -r "\$__f" ] && . "\$__f"; done
exec /usr/bin/bash.real "\$@"
EOF
  chmod 755 /usr/bin/bash /usr/bin/bash.real
  log "bash wrapper ready (/usr/bin/bash -> source ${CACHE}/*/env.sh -> bash.real)"
}

# ---- Runtime function: install tools ----
FORCE=0
for a in "$@"; do
  case "$a" in
    --update|-u) FORCE=1 ;;
  esac
done

ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)  GO_ARCH=amd64 ;;
  aarch64|arm64) GO_ARCH=arm64 ;;
  *) echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac

write_tool_env() {
  local dir="$1"; shift
  mkdir -p "$dir"
  local f="$dir/env.sh"
  {
    echo "# Coding tool environment variables (generated by install.sh, at $dir/env.sh)"
    for line in "$@"; do
      echo "export $line"
    done
  } > "$f"
}

# ---- Go ----
install_go() {
  local dir="$CACHE/go"
  if [ "$FORCE" -eq 0 ] && [ -x "$dir/bin/go" ]; then
    log "Go already installed (skip download)"
  else
    [ "$FORCE" -eq 1 ] && rm -rf "$dir"
    mkdir -p "$dir"
    log "Downloading and installing Go (extract to $dir)..."
    curl -fsSL https://go.dev/dl/?mode=json -o /tmp/golang-dl.json
    GO_VER="$(awk -F'"' '/"version":/{gsub(/^go/,"",$4); print $4; exit}' /tmp/golang-dl.json)"
    TMP="/tmp/go-${GO_VER}.linux-${GO_ARCH}.tar.gz"
    curl -fsSL "https://go.dev/dl/go${GO_VER}.linux-${GO_ARCH}.tar.gz" -o "$TMP"
    tar -C "$dir" -xzf "$TMP" --strip-components=1
    rm -f "$TMP" /tmp/golang-dl.json
    log "Go $GO_VER installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "GOROOT=$dir" \
    "GOPATH=$CACHE/go-pkg" \
    "GOCACHE=$CACHE/go-build" \
    "GOFLAGS=-mod=mod" \
    "PATH=$dir/bin:$CACHE/go-pkg/bin:\$PATH"
}

# ---- Rust ----
install_rust() {
  local rustup_home="$CACHE/rustup"
  local cargo_home="$CACHE/cargo"
  if [ "$FORCE" -eq 0 ] && [ -x "$cargo_home/bin/cargo" ]; then
    log "Rust already installed (skip download)"
  elif [ "$FORCE" -eq 1 ] && [ -x "$cargo_home/bin/rustup" ]; then
    log "Updating Rust ..."
    RUSTUP_HOME="$rustup_home" CARGO_HOME="$cargo_home" "$cargo_home/bin/rustup" update stable >/dev/null 2>&1 || true
    log "Rust updated"
  else
    mkdir -p "$rustup_home" "$cargo_home"
    log "Downloading and installing Rust (directly into $rustup_home / $cargo_home)..."
    export RUSTUP_HOME="$rustup_home"
    export CARGO_HOME="$cargo_home"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o /tmp/rustup-init.sh
    RUSTUP_HOME="$rustup_home" CARGO_HOME="$cargo_home" \
      sh /tmp/rustup-init.sh -y --default-toolchain stable --profile minimal --no-modify-path
    rm -f /tmp/rustup-init.sh
    log "Rust installed"
  fi
  write_tool_env "$cargo_home" \
    "RUSTUP_HOME=$rustup_home" \
    "CARGO_HOME=$cargo_home" \
    "PATH=$cargo_home/bin:$rustup_home/bin:\$PATH"
}

# ---- Node global tools (TypeScript, etc.) ----
install_node_tools() {
  local dir="$CACHE/npm-global"
  if [ "$FORCE" -eq 0 ] && [ -x "$dir/bin/tsc" ]; then
    log "TypeScript already installed (skip download)"
  else
    mkdir -p "$dir"
    log "Installing TypeScript (npm --prefix $dir)..."
    if [ "$FORCE" -eq 1 ]; then npm i -g --prefix "$dir" typescript@latest; else npm i -g --prefix "$dir" typescript; fi
    log "TypeScript installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "npm_config_cache=$CACHE/npm" \
    "npm_config_prefix=$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Lua (official source build) ----
install_lua() {
  local dir="$CACHE/lua"
  if [ "$FORCE" -eq 0 ] && [ -x "$dir/bin/lua" ]; then
    log "Lua already installed (skip download)"
  else
    [ "$FORCE" -eq 1 ] && rm -rf "$dir"
    mkdir -p "$dir"
    log "Downloading and compiling Lua (install to $dir)..."
    LUA_VER="5.4.7"
    curl -fsSL "https://www.lua.org/ftp/lua-${LUA_VER}.tar.gz" -o /tmp/lua.tar.gz
    tar -C /tmp -xzf /tmp/lua.tar.gz
    ( cd "/tmp/lua-${LUA_VER}" && make linux MYCFLAGS="-O2" && make install INSTALL_TOP="$dir" >/dev/null 2>&1 )
    rm -rf "/tmp/lua-${LUA_VER}" /tmp/lua.tar.gz
    log "Lua $LUA_VER installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- PHP (official source build) ----
install_php() {
  local dir="$CACHE/php"
  if [ "$FORCE" -eq 0 ] && [ -x "$dir/bin/php" ]; then
    log "PHP already installed (skip download)"
  else
    [ "$FORCE" -eq 1 ] && rm -rf "$dir"
    mkdir -p "$dir"
    log "Downloading and compiling PHP (official source, minimal CLI, install to $dir)..."
    curl -fsSL 'https://www.php.net/releases/index.php?json' -o /tmp/php-rel.json 2>/dev/null \
      || curl -fsSL 'https://www.php.net/releases/active.php' -o /tmp/php-rel.json 2>/dev/null
    PHP_VER="$(awk -F'"' '/"version":/{v=$4; gsub(/^([0-9]+\.[0-9]+\.[0-9]+).*/,"\\1",v); if(v ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) {print v; exit}}' /tmp/php-rel.json 2>/dev/null)"
    [ -z "$PHP_VER" ] && PHP_VER="8.4.10"
    rm -f /tmp/php-rel.json
    curl -fsSL "https://www.php.net/distributions/php-${PHP_VER}.tar.gz" -o /tmp/php.tar.gz
    tar -C /tmp -xzf /tmp/php.tar.gz
    ( cd "/tmp/php-${PHP_VER}" \
      && ./configure --prefix="$dir" --disable-all --enable-cli \
      && make -j"$(nproc 2>/dev/null || echo 2)" \
      && make install )
    rm -rf "/tmp/php-${PHP_VER}" /tmp/php.tar.gz
    log "PHP $PHP_VER installed (minimal CLI)${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Java (JDK, Adoptium Temurin) ----
install_java() {
  local dir="$CACHE/jdk"
  if [ "$FORCE" -eq 0 ] && [ -x "$dir/bin/java" ]; then
    log "Java already installed (skip download)"
  else
    [ "$FORCE" -eq 1 ] && rm -rf "$dir"
    mkdir -p "$dir"
    log "Downloading and installing Java (Temurin JDK) (extract to $dir)..."
    curl -fsSL 'https://api.adoptium.net/v3/info/available_releases' -o /tmp/java-rel.json
    JAVA_VER="$(awk -F'"' '/most_recent_feature_release/{gsub(/[^0-9]/,"",$3); print $3; exit}' /tmp/java-rel.json)"
    rm -f /tmp/java-rel.json
    case "$GO_ARCH" in amd64) JAVA_ARCH=x64 ;; arm64) JAVA_ARCH=aarch64 ;; *) JAVA_ARCH="$GO_ARCH" ;; esac
    local api="https://api.adoptium.net/v3/binary/latest/${JAVA_VER}/ga/linux/${JAVA_ARCH}/jdk/hotspot/normal/eclipse"
    TMP="/tmp/jdk-${JAVA_VER}.linux-${JAVA_ARCH}.tar.gz"
    curl -fsSL -L "$api" -o "$TMP"
    tar -C "$dir" -xzf "$TMP" --strip-components=1
    rm -f "$TMP"
    log "Java (JDK $JAVA_VER) installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "JAVA_HOME=$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Bun ----
install_bun() {
  local dir="$CACHE/bun"
  if [ "$FORCE" -eq 0 ] && [ -x "$dir/bin/bun" ]; then
    log "Bun already installed (skip download)"
  else
    [ "$FORCE" -eq 1 ] && rm -rf "$dir"
    mkdir -p "$dir"
    log "Downloading and installing Bun (extract to $dir)..."
    curl -fsSL https://api.github.com/repos/oven-sh/bun/releases/latest -o /tmp/bun-rel.json
    BUN_VER="$(awk -F'"' '/"tag_name":/{gsub(/^bun-v/,"",$4); print $4; exit}' /tmp/bun-rel.json)"
    rm -f /tmp/bun-rel.json
    TMP="/tmp/bun-${BUN_VER}.linux-${GO_ARCH}.zip"
    BUN_ARCH="$GO_ARCH"; [ "$BUN_ARCH" = arm64 ] && BUN_ARCH=aarch64
    curl -fsSL "https://github.com/oven-sh/bun/releases/download/bun-v${BUN_VER}/bun-linux-${BUN_ARCH}.zip" -o "$TMP"
    ( cd "$dir" && unzip -oq "$TMP" )
    rm -f "$TMP"
    mkdir -p "$dir/bin"
    local bun_bin
    bun_bin="$(find "$dir" -name bun -type f 2>/dev/null | head -1)"
    if [ -n "$bun_bin" ]; then
      cp "$bun_bin" "$dir/bin/bun"
      chmod +x "$dir/bin/bun"
    fi
    rm -rf "$dir"/bun-linux-* 2>/dev/null || true
    log "Bun $BUN_VER installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Scala (depends on Java) ----
install_scala() {
  if [ ! -x "$CACHE/jdk/bin/java" ]; then
    log "Scala depends on Java; cache/jdk/bin/java not found, installing Java first..."
    install_java
  fi
  local dir="$CACHE/scala"
  if [ "$FORCE" -eq 0 ] && [ -x "$dir/bin/scala-cli" ]; then
    log "Scala (scala-cli) already installed (skip download)"
  else
    [ "$FORCE" -eq 1 ] && rm -rf "$dir"
    mkdir -p "$dir/bin"
    log "Downloading and installing Scala (scala-cli) (install to $dir)..."
    SCALA_ARCH="$GO_ARCH"; [ "$SCALA_ARCH" = arm64 ] && SCALA_ARCH=aarch64
    curl -fsSL "https://github.com/VirtusLab/scala-cli/releases/latest/download/scala-cli-${SCALA_ARCH}-pc-linux.gz" -o /tmp/scala-cli.gz
    gzip -dc /tmp/scala-cli.gz > "$dir/bin/scala-cli"
    chmod +x "$dir/bin/scala-cli"
    rm -f /tmp/scala-cli.gz
    log "Scala (scala-cli) installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Kotlin (depends on Java) ----
install_kotlin() {
  if [ ! -x "$CACHE/jdk/bin/java" ]; then
    log "Kotlin depends on Java; cache/jdk/bin/java not found, installing Java first..."
    install_java
  fi
  local dir="$CACHE/kotlin"
  if [ "$FORCE" -eq 0 ] && [ -x "$dir/kotlinc/bin/kotlin" ]; then
    log "Kotlin already installed (skip download)"
  else
    [ "$FORCE" -eq 1 ] && rm -rf "$dir"
    mkdir -p "$dir"
    log "Downloading and installing Kotlin (extract to $dir)..."
    curl -fsSL https://api.github.com/repos/JetBrains/kotlin/releases/latest -o /tmp/kotlin-rel.json
    KOTLIN_VER="$(awk -F'"' '/"tag_name":/{gsub(/^v/,"",$4); print $4; exit}' /tmp/kotlin-rel.json)"
    rm -f /tmp/kotlin-rel.json
    TMP="/tmp/kotlin-${KOTLIN_VER}.zip"
    curl -fsSL "https://github.com/JetBrains/kotlin/releases/download/v${KOTLIN_VER}/kotlin-compiler-${KOTLIN_VER}.zip" -o "$TMP"
    ( cd "$dir" && unzip -oq "$TMP" )
    rm -f "$TMP"
    local top
    top="$(find "$dir" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | head -1)"
    if [ -n "$top" ] && [ "$(basename "$top")" != kotlinc ]; then
      rm -rf "$dir/kotlinc"
      mv "$top" "$dir/kotlinc"
    fi
    log "Kotlin $KOTLIN_VER installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "PATH=$dir/kotlinc/bin:\$PATH"
}

# ---- Helper: link npm bin entries after --prefix install ----
link_npm_bins() {
  local dir="$1"
  mkdir -p "$dir/bin"
  find "$dir/node_modules" -maxdepth 3 -name package.json ! -path '*/node_modules/.package-lock.json' | while read -r pkg_json; do
    local bins
    bins=$(node -e "
      const p = require('$pkg_json');
      const b = p.bin;
      if (!b) process.exit(0);
      if (typeof b === 'string') console.log(Object.keys(p.bin || {'dummy':1})[0] + '|' + b);
      else Object.entries(b).forEach(([k,v]) => console.log(k + '|' + v));
    " 2>/dev/null) || continue
    [ -z "$bins" ] && continue
    local pkg_dir
    pkg_dir="$(dirname "$pkg_json")"
    echo "$bins" | while IFS='|' read -r name relpath; do
      [ -z "$name" ] && continue
      local src="$pkg_dir/$relpath"
      if [ -f "$src" ]; then
        ln -sf "$src" "$dir/bin/$name"
        chmod +x "$dir/bin/$name"
      fi
    done
  done
}

# ---- Agent CLI: Claude Code ----
install_claude_code() {
  local dir="$CACHE/claude-code"
  local bin="$dir/bin/claude"
  if [ "$FORCE" -eq 0 ] && [ -x "$bin" ]; then
    log "Claude Code already installed (skip)"
  else
    log "Installing Claude Code (npm --prefix $dir)..."
    mkdir -p "$dir"
    npm install --prefix "$dir" "@anthropic-ai/claude-code${FORCE:+@latest}"
    link_npm_bins "$dir"
    log "Claude Code installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "npm_config_cache=$CACHE/npm" \
    "npm_config_prefix=$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Agent CLI: OpenAI Codex ----
install_codex() {
  local dir="$CACHE/codex"
  local bin="$dir/bin/codex"
  if [ "$FORCE" -eq 0 ] && [ -x "$bin" ]; then
    log "OpenAI Codex already installed (skip)"
  else
    log "Installing OpenAI Codex (npm --prefix $dir)..."
    mkdir -p "$dir"
    npm install --prefix "$dir" "@openai/codex${FORCE:+@latest}"
    link_npm_bins "$dir"
    log "OpenAI Codex installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "npm_config_cache=$CACHE/npm" \
    "npm_config_prefix=$dir" \
    "PATH=$dir/bin:\$PATH"
}

# ---- Agent CLI: OpenCode AI ----
install_opencode() {
  local dir="$CACHE/opencode"
  local bin="$dir/bin/opencode"
  if [ "$FORCE" -eq 0 ] && [ -x "$bin" ]; then
    log "OpenCode AI already installed (skip)"
  else
    log "Installing OpenCode AI (npm --prefix $dir)..."
    mkdir -p "$dir"
    npm install --prefix "$dir" "opencode-ai${FORCE:+@latest}"
    link_npm_bins "$dir"
    log "OpenCode AI installed${FORCE:+(updated)}"
  fi
  write_tool_env "$dir" \
    "npm_config_cache=$CACHE/npm" \
    "npm_config_prefix=$dir" \
    "PATH=$dir/bin:\$PATH"
}

setup_shell_source() {
  local snippet='for __f in ${PASEO_CACHE:-/home/paseo/cache}/*/env.sh; do [ -r "$__f" ] && . "$__f"; done'
  local rc="$HOME/.profile"
  touch "$rc" 2>/dev/null || return 0
  grep -q 'cache/\*/env.sh' "$rc" 2>/dev/null && return 0
  printf '\n# paseo coding tool environment variables (source each tool dir'"'"'s env.sh)\n%s\n' "$snippet" >> "$rc"
}

usage() {
  cat <<'USAGE'
Usage: install.sh <subcommand> [options]

  Run once at build time (as root):
    setup-bash-wrap   wrap /usr/bin/bash so it sources each tool's env.sh on startup

  Install coding environments on demand at runtime:
     go            Go toolchain
     rust          Rust toolchain
     java          Java (Temurin JDK)
     bun           Bun JS/TS runtime
     scala         Scala (depends on java, auto-installs JDK first)
     kotlin        Kotlin (depends on java, auto-installs JDK first)
     node-tools    TypeScript etc. npm global packages
     lua           Lua 5.4 (official source build)
     php           PHP official source build, minimal CLI

  Install Agent CLI packages on demand at runtime:
     claude-code   Anthropic Claude Code (npm --prefix)
     codex         OpenAI Codex (npm --prefix)
     opencode      OpenCode AI (npm --prefix)

  Options:
     --update, -u   force reinstall / update to the latest

  Examples:
   install.sh setup-bash-wrap     # only used at image build time
   install.sh go rust             # install Go + Rust
   install.sh claude-code opencode # install Claude Code + OpenCode
   install.sh claude-code codex opencode --update  # upgrade all three agents
   install.sh go --update         # update Go to latest
USAGE
}

# Subcommand dispatch
case "${1:-}" in
  setup-bash-wrap)
    setup_bash_wrap
    exit 0
    ;;
  -h|--help|help|"")
    usage
    exit 0
    ;;
esac

# Runtime install logic
TARGETS=()
for a in "$@"; do
  case "$a" in
    --update|-u) ;;
    -h|--help|help) usage; exit 0 ;;
    *) TARGETS+=("$a") ;;
  esac
done

if [ "${#TARGETS[@]}" -eq 0 ]; then
  usage
  exit 0
fi

for t in "${TARGETS[@]}"; do
  case "$t" in
     go)            install_go ;;
     rust)          install_rust ;;
     java)          install_java ;;
     bun)           install_bun ;;
     scala)         install_scala ;;
     kotlin)        install_kotlin ;;
     node-tools|ts) install_node_tools ;;
     lua)          install_lua ;;
     php)          install_php ;;
     claude-code)  install_claude_code ;;
     codex)        install_codex ;;
     opencode)     install_opencode ;;
      *) echo "Unknown target: $t" >&2; usage; exit 1 ;;
  esac
done

setup_shell_source

log "Done. Each tool's environment variables were written to its install dir's env.sh (e.g. cache/go/env.sh),"
log "and the import statement was written to ~/.profile. Effective immediately inside the paseo process (via the bash wrapper); the interactive shell picks it up on reopen."
