#!/bin/bash
# FreshRSS entrypoint: sub-directory + multi-domain aware.
#
# Responsibilities:
#  1. normalise FRESHRSS_PATH_PREFIX (e.g. "", "/", "/rss", "rss/" -> "/rss")
#  2. export the OIDC paths with that prefix applied, so that mod_auth_openidc serves its
#     callback under the *public* URL and can be reached through every configured domain
#  3. generate the Apache `Alias` serving the public prefix from FreshRSS `p/` directory
#  4. hand over to the upstream entrypoint (cron, Apache, …)
#
# All steps are idempotent: the container can be restarted any number of times.
set -euo pipefail

FRESH_RSS_ROOT=/var/www/FreshRSS
PREFIX_CONF=/etc/apache2/conf-available/freshrss-path-prefix.conf

# --------------------------------------------------------------------------------------------
# 1. Normalise the public path prefix.
# --------------------------------------------------------------------------------------------
# FRESHRSS_PATH_PREFIX: sub-directory the instance is served from. Empty or "/" means the
# instance is at the domain root. Example: "/rss" -> https://example.net/rss/
FRESHRSS_PATH_PREFIX="${FRESHRSS_PATH_PREFIX:-}"
FRESHRSS_PATH_PREFIX="/$(printf '%s' "${FRESHRSS_PATH_PREFIX#/}" | sed 's#/*$##')"
if [ "${FRESHRSS_PATH_PREFIX}" = "/" ]; then
	FRESHRSS_PATH_PREFIX=''
fi
export FRESHRSS_PATH_PREFIX
# Always give Apache an explicit, non-empty value: an undefined ${VAR} expands to nothing and
# would turn `OIDCRedirectURI ${OIDC_REDIRECT_URI}` into a directive without argument.
export OIDC_REDIRECT_URI="${FRESHRSS_PATH_PREFIX}/i/oidc/"
export OIDC_DEFAULT_URL="${FRESHRSS_PATH_PREFIX}/i/"
export OIDC_X_FORWARDED_HEADERS="${OIDC_X_FORWARDED_HEADERS:-X-Forwarded-Host X-Forwarded-Proto X-Forwarded-Port}"

echo "FreshRSS: public path prefix = '${FRESHRSS_PATH_PREFIX:-/ (domain root)}'"

# --------------------------------------------------------------------------------------------
# 1b. Make the data directory usable by the Apache workers.
# --------------------------------------------------------------------------------------------
# FreshRSS keeps per-feed WebSub state in data/PubSubHubbub/ (one directory per topic, plus a key
# file per subscription). Those are created by *root* — the CLI and the refresh cron run as root —
# with mode 0770, which the 022 umask turns into 0750 owned by root:root. The Apache workers run as
# www-data, which is neither the owner nor in group root, so they cannot traverse into those
# directories and every WebSub callback answers 410 "Feed info not found!".
#
# Two things prevent it, and both are needed:
#   * a group-friendly umask, so anything this entrypoint's children create is group-accessible;
#   * setgid on the data directories, so a subdirectory created *later* by root inherits the
#     www-data group instead of root's.
# Without setgid, fixing the permissions once at start-up is not enough: the first actualisation
# after that creates fresh directories with the wrong group again.
# (Invisible when testing on macOS or Windows: Docker Desktop's file sharing bypasses these checks.)
if [ "$(id -u)" = "0" ] && [ -d "${FRESH_RSS_ROOT}/data" ]; then
	umask 002
	www_group=''
	for candidate in www-data apache http; do
		if getent group "$candidate" >/dev/null 2>&1; then
			www_group="$candidate"
			break
		fi
	done
	if [ -n "$www_group" ]; then
		chown -R ":${www_group}" "${FRESH_RSS_ROOT}/data" 2>/dev/null || true
		chmod -R g+rX "${FRESH_RSS_ROOT}/data" 2>/dev/null || true
		chmod -R g+w "${FRESH_RSS_ROOT}/data" 2>/dev/null || true
		find "${FRESH_RSS_ROOT}/data" -type d -exec chmod g+s {} + 2>/dev/null || true
		echo "FreshRSS: data/ is group-writable by ${www_group} (setgid), so WebSub state stays reachable"
	else
		echo "FreshRSS: WARNING — no Apache group {www-data, apache, http} found; WebSub callbacks may answer 410" >&2
	fi
fi

# --------------------------------------------------------------------------------------------
# 2. Serve the public prefix from the FreshRSS `p/` directory.
# --------------------------------------------------------------------------------------------
# The reverse proxy forwards the path unchanged and Apache aliases the prefix, so that:
#  - SCRIPT_NAME carries the prefix, which is how FreshRSS derives its public root;
#  - mod_auth_openidc can match OIDCRedirectURI against the path it actually serves;
#  - PHP session cookies are scoped to a path the browser can match.
: > "${PREFIX_CONF}"
if [ -n "${FRESHRSS_PATH_PREFIX}" ]; then
	# `mod_alias` is disabled by the upstream image as a hardening measure. It is required
	# here: `Alias` is the only mapping that keeps the public prefix in `SCRIPT_NAME`, which
	# FreshRSS uses to derive its public root and mod_auth_openidc uses to match
	# OIDCRedirectURI. The target below is the very same directory as `DocumentRoot`, so no
	# additional path becomes reachable, and the prefix is normalised above.
	a2enmod -q alias
	{
		echo "# Generated by FreshRSS entrypoint — do not edit, regenerated on every start."
		echo "Alias \"${FRESHRSS_PATH_PREFIX}/\" \"${FRESH_RSS_ROOT}/p/\""
		echo "Alias \"${FRESHRSS_PATH_PREFIX}\" \"${FRESH_RSS_ROOT}/p/index.php\""
	} > "${PREFIX_CONF}"
	echo "FreshRSS: serving ${FRESHRSS_PATH_PREFIX}/ -> ${FRESH_RSS_ROOT}/p/ (Apache Alias)"
else
	echo "FreshRSS: served at the domain root, no Alias needed"
fi

# Fail fast on a broken configuration instead of serving 500s.
# envvars first: apache2.conf relies on ${APACHE_RUN_DIR} and friends. It reads optional
# variables, so relax `nounset` around it.
# shellcheck disable=SC1091
if [ -f /etc/apache2/envvars ]; then
	set +u
	. /etc/apache2/envvars
	set -u
fi
if ! apache2 -t >/dev/null 2>&1; then
	echo "FreshRSS: FATAL — invalid Apache configuration:" >&2
	apache2 -t >&2 || true
	exit 1
fi

# --------------------------------------------------------------------------------------------
# 3. Hand over to the upstream entrypoint.
# --------------------------------------------------------------------------------------------
cd "${FRESH_RSS_ROOT}"
exec ./Docker/entrypoint.sh "$@"
